[project]
name = "weatherops"
version = "0.1.0"
description = ""
authors = [
    {name = "Carlos Rafael Senra Brito"}
]
requires-python = ">=3.12"
dependencies = [
    "dvc (>=3.67.0,<4.0.0)",
    "pandas (>=3.0.1,<4.0.0)",
    "pydantic (>=2.12.5,<3.0.0)",
    "plotly (>=6.6.0,<7.0.0)",
    "nbformat (>=5.10.4,<6.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "ipykernel (>=7.2.0,<8.0.0)",
    "pytest (>=9.0.2,<10.0.0)"
]

[tool.poetry]
packages = [
    { include = "core" },
    { include = "src" }
]
